# Generated by Django 5.2.3 on 2025-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_orgao_remove_denuncia_orgao_competente_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='orgaos_responsavel',
            field=models.ManyToManyField(blank=True, help_text='Órgãos pelos quais este usuário é responsável.', to='ocorrencias.orgao'),
        ),
    ]
