# Generated by Django 5.2.3 on 2025-06-17 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='denuncia',
            name='anexo',
            field=models.FileField(blank=True, upload_to='denuncias/anexos/', verbose_name='Anexar Foto/Video'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localização (opcional)'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(default='aberta', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('trafico', 'Tráfico de Drogas'), ('violencia_domestica', 'Violência Doméstica'), ('transito', 'Problemas no Trânsito'), ('roubo', 'Roubo/Furto'), ('vandalismo', 'Vandalismo'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título da Denúncia'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
