# Generated by Django 5.2.3 on 2025-06-17 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_alter_denuncia_options_denuncia_anexo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.AddField(
            model_name='denuncia',
            name='orgao_competente',
            field=models.CharField(choices=[('nenhum', 'Nenhum / Não Designado'), ('pmdf', 'PMDF - Polícia Militar do DF'), ('pcdf', 'PCDF - Polícia Civil do DF'), ('cbmdf', 'CBMDF - Corpo de Bombeiros Militar do DF'), ('sspdf', 'SSP-DF - Secretaria de Segurança Pública do DF'), ('outros_orgaos', 'Outros Órgãos / Sem Classificação Específica')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('crime', 'Crime'), ('violencia', 'Violência Doméstica'), ('ambiental', 'Ambiental'), ('corrupcao', 'Corrupção'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('encaminhada', 'Encaminhada'), ('concluida', 'Concluída'), ('rejeitada', 'Rejeitada')], default='aberta', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
