# Generated by Django 5.2.3 on 2025-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_alter_denuncia_options_denuncia_orgao_competente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do órgão (ex: Polícia Militar do DF)', max_length=100, unique=True)),
                ('sigla', models.CharField(help_text='Sigla do órgão (ex: PMDF)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Órgão Competente',
                'verbose_name_plural': 'Órgãos Competentes',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='orgao_competente',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='orgaos_designados',
            field=models.ManyToManyField(blank=True, help_text='Selecione um ou mais órgãos competentes para esta denúncia.', to='ocorrencias.orgao'),
        ),
    ]
