# Generated by Django 5.2.3 on 2025-06-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_orgao_remove_denuncia_orgao_competente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição (opcional)')),
            ],
            options={
                'verbose_name': 'Categoria de Denúncia',
                'verbose_name_plural': 'Categorias de Denúncias',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='ocorrencias.categoriadenuncia', verbose_name='Categoria'),
        ),
    ]
