# Generated by Django 5.2.3 on 2025-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_categoriadenuncia_alter_denuncia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço da Ocorrência'),
        ),
    ]
