# Generated by Django 5.2.3 on 2025-06-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0006_denuncia_latitude_denuncia_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Endereço da Ocorrência'),
        ),
    ]
