# Generated by Django 5.2.3 on 2025-06-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0008_alter_denuncia_latitude_alter_denuncia_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True),
        ),
    ]
